create table categoria (
	id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
	nome varchar(60) not null,
	descricao varchar(80),
	
	primary key(id)
)